colors = [
    "scarlet",
    "red",
    "crimson",
    "burgundy",
    "ruby",
    "cherry",
    "rose red",
    "tomato red",
    "maroon",
    "vermilion",
    "baby pink",
    "bubblegum pink",
    "fuchsia",
    "salmon",
    "magenta",
    "carnation pink",
    "hot pink",
    "tangerine",
    "peach",
    "apricot",
    "burnt orange",
    "coral",
    "pumpkin",
    "amber",
    "lemon yellow",
    "canary yellow",
    "sunflower yellow",
    "goldenrod",
    "yellow",
    "orange",
    "pink",
    "buttercup",
    "dandelion yellow",
    "mustard",
    "green",
    "lime green",
    "mint green",
    "forest green",
    "olive green",
    "emerald green",
    "jade",
    "chartreuse",
    "blue",
    "sky blue",
    "navy blue",
    "royal blue",
    "turquoise",
    "teal",
    "baby blue",
    "sapphire blue",
    "cornflower blue",
    "cobalt blue",
    "lavender",
    "lilac",
    "violet",
    "plum",
    "amethyst",
    "indigo",
    "mauve",
    "eggplant",
    "brown",
    "chocolate brown",
    "chestnut",
    "caramel",
    "mahogany",
    "auburn",
    "sienna",
    "coffee brown",
    "rust",
    "clear brown",
    "dark brown",
    "golden",
    "gray",
    "ash gray",
    "charcoal gray",
    "slate gray",
    "silver",
    "steel gray",
    "dove gray",
    "smoke gray",
    "black",
    "jet black",
    "ebony",
    "coal black",
    "onyx",
    "midnight black",
    "raven black",
    "white",
    "ivory",
    "snow white",
    "cream",
    "pearl white",
    "vanilla",
    "chalk white",
    "beige",
    "tan",
    "sand",
    "khaki",
    "camel",
    "taupe",
    "buff",
    "biscuit",
    "tawny",
    "blue-black",
    "off-black",
    "light brown",
    "chestnut brown",
    "mahogany",
    "strawberry blonde",
    "ginger",
    "blonde",
    "blond",
    "platinum blonde",
    "ash blonde",
    "golden blonde",
    "dirty blonde",
    "honey blonde",
    "sandy blonde",
    "brownish blonde",
    "brunette",
    "light brunette",
    "dark brunette",
    "chocolate brown",
    "caramel",
    "balayage",
    "ombre",
    "somber",
    "silver",
    "platinum blond",
    "ash blond",
    "golden blond",
    "dirty blond",
    "honey blond",
    "sandy blond",
    "brownish blond",
    "amber",
    "hazel",
    "light green",
    "dark green",
    "light blue",
    "dark blue",
    "violet",
    "gold",
    "purple",
    "cosmos",
    "transparent hazel",
    "transparent brown",
    "transparent gray",
    "transparent green",
    "transparent blue",    
]